## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [2]:
#Do your imports here
import numpy as np

![title](./img/3_2.png
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?
- Solution(https://www.loom.com/share/19c3bf6a87a74918bf31b2b85a778d34)


In [4]:
# okay numpy is great: 
a = np.array([[3,1,2], [-5,4,1], [0,3,-8]])

def inverse_matrix(A):
    mat_inv = np.linalg.inv(A)
    return mat_inv

In [5]:
b = np.array([[1., 2.], [3., 4.]])


inverse_matrix(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

is it reasonable to do it by hand? Only if it is 2x2. If we want to scale it it is crazy
[inverse matrix](https://integratedmlai.com/matrixinverse/)


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?
- Solution (https://www.loom.com/share/45b5e8a0b9424222af0473cf432f6f12)

In [6]:
# Just answer using code --> easy stuff!

A = np.array([[3, 0.6, 4, -3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3 , 9],[-9, 0,0,0]])
C = np.array([[0,1009, -66.7849, 90],[0,5,4,-0.07],[-7.7,0,0,0]])


D = A + B - C


In [7]:
D[1][2]

-2.7

In [8]:
D[2][0]

5.7

In [ ]:

# Harder
# Can you build a matrix solver that can do output the result given 3 matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed.
# solution (https://www.loom.com/share/8f7f34b634f24392a0b646ec697b44c1)
# Solution2 (https://www.loom.com/share/8a41c7b55767466ca63841d589a6444e=)

Implement a matrix solver

In [6]:
A = np.array([[2, 0, 1], [1, 7, 4], [0, 0, 5]])
B = np.array([2, 1, 9])

np.linalg.solve(A,B)



array([ 0.1, -0.9,  1.8])

**numpy way** --> [numpy.linalg.solve](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html)

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?
- Solution (https://www.loom.com/share/9b39a21ac9054591bcbd976decf30275)
A is shape (1, 5) B is shape (5, 3) so output is expected to be (1, 3)




In [14]:
AA = np.array([0.6,-15,2,5,98])
BB = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

CC = np.dot(AA.T, BB)
CC

array([-102.8,  255.2,  595.6])

In [16]:
#value of C13

CC[2]

595.6